# Elastic Beanstalk CLI configuration
global:
  application_name: next-ssr-app
  default_ec2_keyname: null
  default_platform: Node.js 20 running on 64bit Amazon Linux 2023/6.5.1 # Explicitly specify Node.js 20 platform
  default_region: us-east-1
  instance_type: t2.micro
  workspace_type: Application